name: TommiT
favicon: null
layout_spectrum: 0.9073894910980016
typography_spectrum: 0.6469665213953704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10552755929529667
  lightness: 0.24733765446580946
  saturation: 0.48525542044080794
  rhythmicContrast: 0.9462932692840695
purpose: []
